app/authentication/routes.py
from forms import UserLoginForm
from models import User, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash

# imports for flask login 
from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            
            email = form.email.data
            password = form.password.data
            print(email, password)

            user = User(email, password = password)

            db.session.add(user)
            db.session.commit()



            flash(f'You have successfully created a user account {email}', 'User-created')
            return redirect('https://capstone-project-backend-x3j1.onrender.com/signin')
        
    except:
        raise Exception('Invalid form data: Please check your form')
    return render_template('sign_up.html', form=form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    
    try:
        if request.method == 'POST' and form.validate_on_submit():
            
            email = form.email.data
            password = form.password.data
            print(email,password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successful in your initiation.', 'auth-success')
                return redirect('https://timely-wisp-4ed4f4.netlify.app/#/')
            else:
                flash('You do not have access to this content.', 'auth-failed')
                return redirect('https://capstone-project-backend-x3j1.onrender.com/signin')
    except:
        raise Exception('Invalid Form Data: Please Check your Form')
    return render_template('sign_in.html', form=form)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect('https://timely-wisp-4ed4f4.netlify.app/#/')

app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Digital Music Application</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 fixed-top">
        <div class="container">
            <a href="https://timely-wisp-4ed4f4.netlify.app/#/" class="navbar-brand">Digial Music Application</a>
            <button 
                class="navbar-toggler" 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#navmenu"
            ><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="https://timely-wisp-4ed4f4.netlify.app/#/" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('site.profile') }}" class="nav-link">Profile</a>
                    </li> 
                   
                    </li>
                            {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a>
                    </li>
                            {% else %}
                    
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signup') }}" class="nav-link">Sign Up</a>
                    </li>
                            {% endif %}                 
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="first_name-field">
            {{ form.first_name.label }}
            {{ form.first_name(class = 'form-control', placeholder = 'Place first name here ') }}
        </fieldset>
    </div>
        <fieldset id="last_name-field">
            {{ form.last_name.label }}
            {{ form.last_name(class = 'form-control', placeholder = 'Place last name here ') }}
        </fieldset>

        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder = 'Place email here ') }}
        </fieldset>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place password here ") }}
        </fieldset>

        <!-- Submit button area -->
        {{ form.submit_button(class = "btn btn-primary btn-block mt-2")}}

</form>